name: Download backend

inputs:
  arch:
    description: Architecture arm64 or x64
    required: false
    default: 'x64'

runs:
  using: 'composite'
  steps:
    - name: Download backend
      run: yarn download:backend ${{ inputs.arch }}
