export enum Keys {
  ENTER = 'enter',
  SPACE = ' ',
  ESCAPE = 'escape',
  TAB = 'tab',
  BACKSPACE = 'backspace',
  F2 = 'f2',
  ALT = 'alt',
  SHIFT = 'shift',
  CTRL = 'control',
  META = 'meta',
  ARROW_DOWN = 'arrowdown',
  ARROW_UP = 'arrowup',
  ARROW_LEFT = 'arrowleft',
  ARROW_RIGHT = 'arrowright',
  PAGE_UP = 'pageup',
  PAGE_DOWN = 'pagedown',
  END = 'end',
  HOME = 'home',
}
