# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

aliases:
  ui-deps-cache-key: &uiDepsCacheKey
    key: ui-deps-{{ checksum "yarn.lock" }}

jobs:
  unit-tests-ui:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - restore_cache:
          <<: *uiDepsCacheKey
      - run:
          name: Install dependencies
          command: |
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Unit tests UI
          command: |
            yarn test:cov --ci --silent
      - save_cache:
          <<: *uiDepsCacheKey
          paths:
            - ~/.cache/yarn


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  frontend-tests:
    jobs:
      - unit-tests-ui
