name: Setup E2E Environment
description: Common setup steps for E2E jobs

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'

    - name: Download linux artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: ./release

    - name: Setup e2e tests
      working-directory: ./tests/e2e
      shell: bash
      run: |
        npm install -g @vscode/vsce
        yarn install
        yarn compile
        ls -R dist/tests/
