export enum OAuthSocialSource {
  Browser = 'browser',
  ListOfDatabases = 'list of databases',
  WelcomeScreen = 'welcome screen',
  BrowserContentMenu = 'browser content menu',
  BrowserFiltering = 'browser filtering',
  BrowserSearch = 'browser search',
  RediSearch = 'workbench RediSearch',
  RedisJSON = 'workbench RedisJSON',
  RedisTimeSeries = 'workbench RedisTimeSeries',
  RedisGraph = 'workbench RedisGraph',
  RedisBloom = 'workbench RedisBloom',
  Autodiscovery = 'autodiscovery',
  SettingsPage = 'settings',
  ConfirmationMessage = 'confirmation message',
  Workbench = 'workbench',
  Tutorials = 'tutorials',
  EmptyDatabasesList = 'empty_db_list',
  DatabasesList = 'db_list',
  DiscoveryForm = 'discovery form',
  UserProfile = 'user profile',
  AiChat = 'ai chat',
}
