enum StorageItem {
  databasesCount = 'databasesCount',
  databasesSorting = 'databasesSorting',
  theme = 'theme',
  browserViewType = 'browserViewType',
  browserSearchMode = 'browserSearchMode',
  cliClientUuid = 'cliClientUuid',
  cliResizableContainer = 'cliResizableContainer',
  cliInputHistory = 'cliInputHistory',
  cliIsShowHelper = 'cliIsShowHelper',
  segmentAnonymousId = 'ajs_anonymous_id',
  wbClientUuid = 'wbClientUuid',
  wbInputHistory = 'wbInputHistory',
  isEnablementAreaMinimized = 'isEnablementAreaMinimized',
  treeViewDelimiter = 'treeViewDelimiter',
  treeViewSort = 'treeViewSort',
  autoRefreshRate = 'autoRefreshRate',
  bulkActionDeleteId = 'bulkActionDeleteId',
  dbConfig = 'dbConfig_',
  RunQueryMode = 'RunQueryMode',
  wbCleanUp = 'wbCleanUp',
  viewFormat = 'viewFormat',
  wbGroupMode = 'wbGroupMode',
  keyDetailSizes = 'keyDetailSizes',
  featuresHighlighting = 'featuresHighlighting',
  dbIndex = 'dbIndex_',
  recommendationsViewed = 'recommendationsViewed',
  showHiddenRecommendations = 'showHiddenRecommendations',
  OAuthJobId = 'OAuthJobId',
  OAuthAgreement = 'OAuthAgreement',
  cliDatabase = 'cliDatabase',
  databaseId = 'databaseId',
  openTreeNode = 'openTreeNode',
  openTreeDatabase = 'openTreeDatabase',
}

export { StorageItem }

export enum ConfigDBStorageItem {
  slowLogDurationUnit = 'slowLogDurationUnit',
}
