name: AWS

on:
  workflow_call:
    inputs:
      enterprise:
        description: Enterprise build
        type: boolean
        default: false
        required: false

env:
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  release-private:
    name: Release s3 private
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./release

    - run: ls -R ./release

    - name: Publish private
      run: |
        chmod +x .github/build/sum_sha256.sh
        .github/build/sum_sha256.sh
        applicationVersion=$(jq -r '.version' package.json)

        if [ "${{ inputs.enterprise }}" = "true" ]; then
          uploadPath="s3://${AWS_BUCKET_NAME}/private/vscode-enterprise/${applicationVersion}"
        else
          uploadPath="s3://${AWS_BUCKET_NAME}/private/vscode/${applicationVersion}"
        fi

        aws s3 cp release/ $uploadPath --recursive
