name: Build linux pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: Environment for build
        required: false
        default: 'staging'
        type: string

jobs:
  build:
    name: Build linux
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4
      # SSH
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true

    - name: Setup Node
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '20.15'

    - name: Install dependencies for root package.js
      run: yarn install --frozen-lockfile

    - name: Download backend
      uses: ./.github/actions/download-backend

    - name: Set RI_SEGMENT_WRITE_KEY to .env file
      run: echo "RI_SEGMENT_WRITE_KEY='${{ env.RI_SEGMENT_WRITE_KEY }}'" >> ${{ env.envFile }}

    - name: Build linux package (production)
      if: inputs.environment == 'production'
      run: |
        yarn package:prod --target linux-x64 --out ${packagePath}

    - name: Build linux package (staging)
      if: inputs.environment == 'staging'
      run: |
        sed -i "s/^RI_APP_FOLDER_NAME=.*/RI_APP_FOLDER_NAME='.redis-for-vscode-stage'/" ${{ env.envFile }}
        yarn package:stage --target linux-x64 --out ${packagePath}

    - uses: actions/upload-artifact@v4
      name: Upload extension artifact
      with:
        name: linux-build
        path: |
          release/redis-for-*.vsix

    env:
      envFile: '.env'
      packagePath: './release/redis-for-vscode-extension-linux-x64.vsix'
      RI_SEGMENT_WRITE_KEY: ${{ secrets.RI_SEGMENT_WRITE_KEY }}
