name: Build linux pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: Environment for build
        required: false
        default: 'staging'
        type: string

jobs:
  build:
    name: Build linux
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}

    steps:
    # SSH
    # - name: Setup upterm session
    #   uses: mxschmitt/action-tmate@v3 #1 better

    - uses: actions/checkout@v4

    # - name: Install all libs and dependencies
    #   uses: ./.github/actions/install-all-build-libs
    - name: Setup Node
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '20.15'
        # disable cache for windows
        # https://github.com/actions/setup-node/issues/975
        cache: 'yarn'

    # - name: Setup Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.11'

    - name: Install dependencies for root package.js
      run: yarn install --frozen-lockfile


    # - run: rm -rf tsconfig.json

    - name: Download backend
      uses: ./.github/actions/download-backend

    # - run: ls -la ./scripts
    # - run: yarn download:backend
    # - run: yarn download:backend ${{ inputs.arch }}

    - name: Set RI_SEGMENT_WRITE_KEY to .env file
      run: echo "RI_SEGMENT_WRITE_KEY='$RI_SEGMENT_WRITE_KEY'" >> $envFile

    - name: Build linux package (production)
      if: inputs.environment == 'production'
      run: |
        yarn package:prod --target linux-x64 --out ${packagePath}

    - name: Build linux package (staging)
      if: inputs.environment == 'staging'
      run: |
        sed -i "s/^RI_APP_FOLDER_NAME=.*/RI_APP_FOLDER_NAME='.redis-for-vscode-stage'/" $envFile
        yarn package:stage --target linux-x64 --out ${packagePath}

    - uses: actions/upload-artifact@v4
      name: Upload extension artifact
      with:
        name: linux-build
        path: |
          release/redis-for-*.vsix

    env:
      envFile: '.env'
      packagePath: './release/redis-for-vscode-extension-linux-x64.vsix'
      RI_SEGMENT_WRITE_KEY: ${{ secrets.RI_SEGMENT_WRITE_KEY }}
