name: Build windows pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: Environment for build
        required: false
        default: 'staging'
        type: string

jobs:
  build:
    name: Build windows
    runs-on: windows-2022
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4

    - name: Install all libs and dependencies
      uses: ./.github/actions/install-all-build-libs

    - name: Download backend
      uses: ./.github/actions/download-backend

    - name: Set RI_SEGMENT_WRITE_KEY to .env file
      run: echo "RI_SEGMENT_WRITE_KEY='${{ env.RI_SEGMENT_WRITE_KEY }}'" >> ${{ env.envFile }}

    - name: Build windows package (production)
      if: inputs.environment == 'production'
      run: |
        yarn package:prod --target win32-x64 --out ${{ env.packagePath }}

    - name: Build windows package (staging)
      if: inputs.environment == 'staging'
      run: |
        sed -i "s/^RI_APP_FOLDER_NAME=.*/RI_APP_FOLDER_NAME='.redis-for-vscode-stage'/" ${{ env.envFile }}
        yarn package:stage --target win32-x64 --out ${{ env.packagePath }}

    - uses: actions/upload-artifact@v4
      name: Upload extension artifact
      with:
        name: windows-build
        path: |
          release/redis-for-*.vsix

    env:
      envFile: '.env'
      packagePath: './release/redis-for-vscode-extension-win-x64.vsix'
      RI_SEGMENT_WRITE_KEY: ${{ secrets.RI_SEGMENT_WRITE_KEY }}
