name: ❗ Release (prod)

on:
  push:
    branches:
      - 'latest'
      - 'latest-enterprise'

jobs:
  tests-prod:
    name: Run all tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      group_tests: 'without_e2e'
      pre_release: true

  builds-prod:
    name: Create all builds for release
    uses: ./.github/workflows/build.yml
    needs: tests-prod
    secrets: inherit
    with:
      environment: 'production'
      target: 'all'
      enterprise: ${{ github.ref_name == 'latest-enterprise' }}

  e2e-linux-tests:
    name: E2E Docker tests
    needs: builds-prod
    uses: ./.github/workflows/tests-e2e-linux.yml
    secrets: inherit

  aws-prod:
    name: Realse to AWS S3
    uses: ./.github/workflows/aws.yml
    needs: builds-prod
    secrets: inherit
    with:
      enterprise: ${{ github.ref_name == 'latest-enterprise' }}
