name: Tests UI
on:
  workflow_call:

env:
  SLACK_AUDIT_REPORT_CHANNEL: ${{ secrets.SLACK_AUDIT_REPORT_CHANNEL }}
  SLACK_AUDIT_REPORT_KEY: ${{ secrets.SLACK_AUDIT_REPORT_KEY }}
  REPORT_NAME: "report-vscode-fe"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Frontend tests
    steps:
    - uses: actions/checkout@v4

    - name: Install all libs and dependencies
      uses: ./.github/actions/install-all-build-libs

    - name: Unit tests UI
      run: yarn test:cov

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.REPORT_NAME }}
        compression-level: 0
        path: report

    - name: Deploy report
      uses: RedisInsight/RedisInsight/.github/actions/deploy-test-reports@873a0ebf55c85d3127bb4efb4d0636d9ab838226
      if: always()
      with:
        group: 'report'
        AWS_BUCKET_NAME_TEST: ${{ vars.AWS_BUCKET_NAME_TEST }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get current date
      id: date
      if: always()
      uses: RedisInsight/RedisInsight/.github/actions/get-current-date@873a0ebf55c85d3127bb4efb4d0636d9ab838226

    - name: Add link to report in the workflow summary
      if: always()
      run: |
        link="${{ vars.DEFAULT_TEST_REPORTS_URL }}/${{ steps.date.outputs.date }}/${{ github.run_id }}/${{ env.REPORT_NAME }}/index.html"
        echo "[${link}](${link})" >> $GITHUB_STEP_SUMMARY
