name: Tests E2E Linux
on:
  workflow_call:
    inputs:
      report:
        description: Send report to Slack
        required: false
        default: false
        type: boolean

env:
  SLACK_TEST_REPORT_KEY: ${{ secrets.SLACK_TEST_REPORT_KEY }}

jobs:
  e2e-linux-tests:
    runs-on: ubuntu-latest
    name: E2E tests
    container:
      image: docker:latest
      options: --privileged
      volumes:
        - /usr/src/app/results:/usr/src/app/results
        - /usr/src/app/report:/usr/src/app/report
    strategy:
      fail-fast: false
      matrix:
        # Number of threads to run tests
        # parallel: [0, 1, 2, 3]
        parallel: [0]

    steps:
    - uses: actions/checkout@v4

    # - name: Setup repository
    #   run: git config --global --add safe.directory /__w/RedisInsight/Redis-for-VS-Code

    - name: Start Xvfb
      run: |
        apt-get install -y xvfb net-tools
        Xvfb :99 -screen 0 1920x1080x24 &

    - name: Download linux artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: ./release

    - name: Setup e2e tests
      working-directory: ./tests/e2e
      run: |
        yarn install
        yarn compile
        ls -R dist/tests/

    - name: Generate short list of the test files
      working-directory: ./tests/e2e
      run: |
        testFiles=$(find tests -type f -name '*.e2e.js' | sort | awk "NR % 4 == ${{ matrix.parallel }}")
        echo $testFiles

        # Multi-Line value
        echo "TEST_FILES<<EOF" >> $GITHUB_ENV
        echo "$testFiles" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Run tests
      run: |
        .github/e2e/test.app.sh

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report-linux-node-${{ matrix.parallel }}
        path: /usr/src/app/report

    - name: Send report to Slack
      if: inputs.report && always()
      run: |
        APP_BUILD_TYPE="VSCode (Linux)" node ./.github/e2e/e2e-results.js
        # curl -H "Content-type: application/json" --data @e2e.report.json -H "Authorization: Bearer $SLACK_TEST_REPORT_KEY" -X POST https://slack.com/api/chat.postMessage

    - name: Generate test results for ${{ matrix.parallel }}th node
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Test results: E2E (linux) ${{ matrix.parallel }}th node'
        path: /usr/src/app/results/results.xml
        reporter: java-junit
        list-tests: 'failed'
        list-suites: 'failed'
        fail-on-error: 'false'

  merge-artifacts:
    runs-on: ubuntu-latest
    needs: e2e-linux-tests
    steps:
    - name: Merge report artifacts
      id: merge-artifacts
      uses: actions/upload-artifact/merge@v4
      with:
        name: report-e2e-linux
        pattern: report-linux-node-*
        delete-merged: true
