name: ✅ Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'e2e/**'

  workflow_dispatch:
    inputs:
      group_tests:
        description: Run group of tests
        default: 'all'
        type: choice
        options:
          - all
          - without_e2e
          - only_e2e

  workflow_call:
    inputs:
      group_tests:
        description: Run group of tests
        type: string
        default: 'all'
      pre_release:
        description: Is pre-release
        default: false
        type: boolean

jobs:
  frontend-tests:
    if: inputs.group_tests == 'all' || inputs.group_tests == 'without_e2e' || startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/tests-frontend.yml
    secrets: inherit

  e2e-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: inputs.group_tests == 'all' || inputs.group_tests == 'only_e2e' || startsWith(github.ref_name, 'e2e/')
    environment: ${{ startsWith(github.ref_name, 'e2e/') && 'e2e-approve' || 'staging' }}
    name: Approve E2E tests
    steps:
      - uses: actions/checkout@v4

  build-linux:
    uses: ./.github/workflows/pipeline-build-linux.yml
    needs: e2e-approve
    secrets: inherit

  e2e-linux-test:
    needs: build-linux
    uses: ./.github/workflows/tests-e2e-linux.yml
    secrets: inherit
